#!/usr/bin/env python
import sys
import warnings
import os
from datetime import datetime
from pathlib import Path

from stock.crew import StockPicker

warnings.filterwarnings("ignore", category=SyntaxWarning, module="pysbd")


def save_as_pdf(content: str, output_path: str):
    """Save the crew result as a formatted PDF."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    from reportlab.lib.enums import TA_CENTER, TA_LEFT

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        fontSize=22,
        textColor=colors.HexColor("#1a1a2e"),
        alignment=TA_CENTER,
        spaceAfter=6,
    )

    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#555555"),
        alignment=TA_CENTER,
        spaceAfter=20,
    )

    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=11,
        leading=18,
        textColor=colors.HexColor("#222222"),
        spaceAfter=10,
    )

    story = []

    # Header
    story.append(Paragraph("📈 Stock Investment Report", title_style))
    story.append(Paragraph(f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#1a1a2e")))
    story.append(Spacer(1, 0.5 * cm))

    # Body — split on newlines, render each line as a paragraph
    for line in content.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.3 * cm))
            continue

        # Make markdown-style headers bold
        if line.startswith("## "):
            story.append(Paragraph(f"<b>{line[3:]}</b>", ParagraphStyle(
                "H2", parent=body_style, fontSize=14, textColor=colors.HexColor("#1a1a2e"), spaceBefore=12
            )))
        elif line.startswith("# "):
            story.append(Paragraph(f"<b>{line[2:]}</b>", ParagraphStyle(
                "H1", parent=body_style, fontSize=16, textColor=colors.HexColor("#1a1a2e"), spaceBefore=14
            )))
        elif line.startswith("**") and line.endswith("**"):
            story.append(Paragraph(f"<b>{line[2:-2]}</b>", body_style))
        else:
            # Escape special XML chars for ReportLab
            line = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(line, body_style))

    # Footer spacer
    story.append(Spacer(1, 1 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    story.append(Paragraph("Generated by StockPicker AI Crew", ParagraphStyle(
        "Footer", parent=styles["Normal"], fontSize=9, textColor=colors.grey, alignment=TA_CENTER
    )))

    doc.build(story)


def run():
    """Run the research crew and save output as PDF."""
    inputs = {
        "sector": "Technology",
        "current_date": str(datetime.now())
    }

    # Run the crew
    result = StockPicker().crew().kickoff(inputs=inputs)

    print("\n\n=== FINAL DECISION ===\n\n")
    print(result.raw)

    # Save to PDF
    output_dir = Path("output")
    output_dir.mkdir(exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    pdf_path = output_dir / f"stock_report_{timestamp}.pdf"

    save_as_pdf(result.raw, str(pdf_path))

    print(f"\n✅ PDF report saved to: {pdf_path.resolve()}")


if __name__ == "__main__":
    run()